sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: bind-debian-8
    - INSTANCE: bind-debian-9
    - INSTANCE: bind-ubuntu-1604
    - INSTANCE: bind-ubuntu-1804
    - INSTANCE: bind-fedora-27
    - INSTANCE: bind-centos-7

script:
  - bundle exec kitchen verify ${INSTANCE}

